name: fastapi-recommendation-system
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - fastapi
  - uvicorn
  - pandas
  - numpy
  - scikit-learn
  - sqlalchemy
  - pydantic
  - conda-forge::surprise
  - pymysql
  - python-dotenv
  - pip:
    - scikit-surprise
