name: fastapi-recommendation-system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - fastapi=0.68.1
  - uvicorn=0.15.0
  - pandas=1.3.3
  - numpy=1.21.2
  - scikit-learn=0.24.2
  - sqlalchemy=1.4.25
  - pydantic=1.8.2
  - pymysql=1.0.2
  - python-dotenv=0.19.1
  - conda-forge::scikit-surprise=1.1.1
  - pip
