name: Docker Build and Run

on:
  push:
    branches:
      - main  # Trigger the workflow on main branch pushes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Load .env.example file
        run: |
          if [ -f .env.example ]; then
            export $(cat .env.example | grep -v '#' | awk '/=/ {print $1}')
          fi

      - name: Export secrets as environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: adhamfaraitodi/fastapi-recommendation-system:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

